# Generated by Django 5.0.4 on 2024-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delayinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linename', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('departurestation', models.CharField(max_length=30)),
                ('arrivalstation', models.CharField(max_length=30)),
                ('delaystatus', models.BooleanField(default=False)),
                ('delayreason', models.TextField(blank=True, null=True)),
                ('scrapedtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
